<?
$aMenuLinks = Array(
    Array(
        "Главная",
        "main/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Каталог",
        "catalog_top/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Новости",
        "news_top/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "О магазине",
        "about_top/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Контакты",
        "contact_top/",
        Array(),
        Array(),
        ""
    )
);
?>